'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpDown, ChevronLeft, ChevronRight, CircleUserRound, Coins, Headphones, Menu, Minus, Plus, Search, Send, ShoppingBag, ShoppingCart, Volume2, VolumeX, Wallet, X, Zap } from 'lucide-react'
import { applyPity, calculateChance, ECONOMY_SCALE, filterCatalog, findAffordableCatalogPrice, isWinningRoll, MAX_BALANCE, normalizeGameState, rarityColor, upgradeLanding, validateUpgradeStake } from '@/lib/game-logic'
import { playArcadeStart, playArcadeStep, playUpgradeClick, playUpgradeResult, startSpinSound, stopSpinSound } from '@/lib/game-audio'
import { applyClickBurst, claimCoinSlot, COIN_SLOT_VALUE, getCoinFarmStatus, MAX_COIN_SLOTS } from '@/lib/coin-farm'
import { initialGameState as initial, money, secureRandomValue, type CatalogState, type GameMode, type GameState, type History, type Skin } from '@/lib/game-model'
import { PlinkoMode } from '@/components/game/modes/plinko-mode'
import { ArcadeMode } from '@/components/game/modes/arcade-mode'
import { CasesMode } from '@/components/game/modes/cases-mode'
import { instanceId, Mark, skinIdFromInstance, SkinImage } from '@/components/game/shared'
import { CasinoEventLayer, LevelBadge, OnlineCounter, RewardsModal } from '@/components/casino/casino-hud'
import { trackResult, trackWager } from '@/lib/casino-system'

const cdn = 'https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/'
const skins: Skin[] = [
  { id:'p250', weapon:'P250', name:'Sand Dune', price:125.75*ECONOMY_SCALE, image:'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLhzMOwwjFU0OGvZqBSLPmUBnPelesn5-RrSXDlwRhx5TjSwtmocCifPwQpDpshReBfsxPrk4DhNu3jshue1dy8VcXxuA/360fx360f', rarity:'common' },
  { id:'p90', weapon:'P90', name:'Sand Spray', price:289.51*ECONOMY_SCALE, image:`${cdn}weapon_p90_sp_spray_sand_light_large.18ac7e644639b8756fa3984055a493c5d7fc8249.png`, rarity:'rare' },
  { id:'sg', weapon:'SG 553', name:'Army Sheen', price:475.39*ECONOMY_SCALE, image:'https://community.fastly.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopb3wflFf0v73cC9P9eOlnImFksj4OrzZgiVVsZR0jLjFo96giQ3t_UJrazr2INSWIQJvZ17Z_Ve8kuq-hpbo6Jmf1zI97f6CtMPI/360fx360f', rarity:'common' },
  { id:'famas', weapon:'FAMAS', name:'Colony', price:720.68*ECONOMY_SCALE, image:'https://cdn.cs2.ad/cs2-skins/9b3b005674618aaf947fadc3873edcb4.png', rarity:'rare' },
  { id:'cz', weapon:'CZ75-Auto', name:'Imprint', price:980.50*ECONOMY_SCALE, image:`${cdn}weapon_cz75a_gs_cz75_tread_light_large.8c276db730bb33477aaa52f7a23825f295e14364.png`, rarity:'rare' },
  { id:'usp', weapon:'USP-S', name:'Forest Leaves', price:1450.23*ECONOMY_SCALE, image:`${cdn}weapon_usp_silencer_sp_leaves_light_large.a71c8dc482fea4aaa1c6b5c115e370a7e134ddfd.png`, rarity:'epic' },
  { id:'five', weapon:'Five-SeveN', name:'Coolant', price:2280.26*ECONOMY_SCALE, image:'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLOzLhRlxfbGTjVb09ijl5SYqPDmNr7fqWNU6dNoxOyTrY6s2layqkJoa2D1cYCUJAQ3YA3Sr1Ptwum8g5Dtvs-bnSQys3I8pSGKQLG11w0/360fx360f', rarity:'rare' },
  { id:'nova', weapon:'Nova', name:'Forest Leaves', price:3975.83*ECONOMY_SCALE, image:'https://cache.steamanalyst.com/4b4fb67b6d552c1b2639793654374c048f2830ed.webp', rarity:'epic' },
  { id:'lead', weapon:'USP-S', name:'Lead Conduit', price:5890.51*ECONOMY_SCALE, image:`${cdn}weapon_usp_silencer_sp_leaves_light_large.a71c8dc482fea4aaa1c6b5c115e370a7e134ddfd.png`, rarity:'epic' },
  { id:'biz', weapon:'PP-Bizon', name:'Candy Apple', price:8250.35*ECONOMY_SCALE, image:`${cdn}weapon_bizon_so_red_light_large.0ee9cada135b87096b447521a05c0a2d437bf9ff.png`, rarity:'rare' },
  { id:'glock', weapon:'Glock-18', name:'Off World', price:12950.93*ECONOMY_SCALE, image:'https://imageproxy.csmarketcap.com/insecure/rs:fit:500:500:0/g:nowe/f:webp/plain/https://images.csmarketcap.com/i/730-glock-18-off-world-factory-new.webp', rarity:'epic' },
  { id:'dual', weapon:'Dual Berettas', name:'Colony', price:18750.50*ECONOMY_SCALE, image:`${cdn}weapon_elite_so_space_marine_light_large.101c6b29315d37db050a4c7817a4c11517baa167.png`, rarity:'common' },
  { id:'vulcan', weapon:'AK-47', name:'Vulcan', price:48500.25*ECONOMY_SCALE, image:`${cdn}weapon_ak47_cu_ak47_rubber_light_large.5836c38d3037a5a1f90ffdc8c9d0b94367ca8efd.png`, rarity:'legendary' },
  { id:'st-vulcan', weapon:'StatTrak™ AK-47', name:'Vulcan', price:112500.75*ECONOMY_SCALE, image:`${cdn}weapon_ak47_cu_ak47_rubber_light_large.5836c38d3037a5a1f90ffdc8c9d0b94367ca8efd.png`, rarity:'legendary' },
  { id:'st-printstream', weapon:'StatTrak™ USP-S', name:'Printstream', price:198750.25*ECONOMY_SCALE, image:`${cdn}weapon_usp_silencer_cu_usp_printstream_light_large.9e40ae25d853d6a24bcf0d1b0fd2292b29a33266.png`, rarity:'legendary' },
  { id:'st-asiimov', weapon:'StatTrak™ AWP', name:'Asiimov', price:325000.50*ECONOMY_SCALE, image:`${cdn}weapon_awp_cu_awp_asimov_light_large.32d9045f8a2bcd13ca18390cc9fd82026e7195ab.png`, rarity:'legendary' },
  { id:'fade', weapon:'AWP', name:'Fade', price:575000.50*ECONOMY_SCALE, image:'/weapons/awp-fade.png', rarity:'legendary' },
  { id:'st-fire-serpent', weapon:'StatTrak™ AK-47', name:'Fire Serpent', price:890000.25*ECONOMY_SCALE, image:`${cdn}weapon_ak47_cu_fireserpent_light_large.761384b7451f4f37f9e74bca09527e2c5a152d0c.png`, rarity:'legendary' },
  { id:'st-howl', weapon:'StatTrak™ M4A4', name:'Howl', price:1250000.75*ECONOMY_SCALE, image:`${cdn}weapon_m4a1_cu_m4a1_howling_light_large.c64a23b2d79626b31746819de93f3ef4eeb295d5.png`, rarity:'legendary' },
  { id:'st-dlore', weapon:'StatTrak™ AWP', name:'Dragon Lore', price:1875000.50*ECONOMY_SCALE, image:`${cdn}weapon_awp_cu_medieval_dragon_awp_light_large.58d8a7e8238b60f7f6d3c4c8ca3a0e8ed26e8f35.png`, rarity:'legendary' },
  { id:'knife', weapon:'Butterfly Knife', name:'Ruby', price:2450000.15*ECONOMY_SCALE, image:'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KW1Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpotLu8JAllx8zPYgJS7ciknYO0m_7zO6-fxT0E7cN_273FrI2l3wXk_EA9YWn6I4bEIQI3Yw7SqAK3xLrr0JO-6pjNwSZ9-n51BYWnYWE/360fx360f', rarity:'legendary' },
  { id:'st-knife', weapon:'StatTrak™ Butterfly Knife', name:'Ruby', price:3850000.50*ECONOMY_SCALE, image:'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KW1Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpotLu8JAllx8zPYgJS7ciknYO0m_7zO6-fxT0E7cN_273FrI2l3wXk_EA9YWn6I4bEIQI3Yw7SqAK3xLrr0JO-6pjNwSZ9-n51BYWnYWE/360fx360f', rarity:'legendary' },
  { id:'souvenir-dlore', weapon:'Souvenir AWP', name:'Dragon Lore', price:5250000.25*ECONOMY_SCALE, image:`${cdn}weapon_awp_cu_medieval_dragon_awp_light_large.58d8a7e8238b60f7f6d3c4c8ca3a0e8ed26e8f35.png`, rarity:'legendary' },
  { id:'st-gungnir', weapon:'StatTrak™ AWP', name:'Gungnir', price:6750000.75*ECONOMY_SCALE, image:`${cdn}weapon_awp_gs_awp_gungnir_light_large.f5f6e4c4c4bfae0fa375c26955d7c23e5d65da09.png`, rarity:'legendary' },
  { id:'gem-knife', weapon:'StatTrak™ Karambit', name:'Blue Gem 387', price:8250000.50*ECONOMY_SCALE, image:`${cdn}weapon_knife_karambit_am_case_hardened_light_large.472a5e0f82385f815e28574cf2986cbea84a63c4.png`, rarity:'legendary' },
  { id:'ultimate', weapon:'Souvenir AWP', name:'Dragon Lore Titan', price:9999999.99*ECONOMY_SCALE, image:`${cdn}weapon_awp_cu_medieval_dragon_awp_light_large.58d8a7e8238b60f7f6d3c4c8ca3a0e8ed26e8f35.png`, rarity:'legendary' },
]

const copy = {
 en:{online:'Online · local',total:'Total upgrades',topup:'Top up',likes:'Community bonus',gifts:'Daily gift',likeText:'Thanks for supporting UPGRADER. Your virtual community bonus is ready.',claim:'CLAIM 250 COINS',claimed:'CLAIMED',giftText:'Open your daily virtual reward.',open:'OPEN GIFT',skins:'MY SKINS',market:'MARKET',shop:'SHOP',empty:'Your inventory is empty',emptySub:'Buy a skin in Market or win an upgrade.',selectSource:'Select skins or balance to use.',selectTarget:'Select a skin for upgrade',upgrade:'Upgrade',balance:'Balance amount:',settings:'LANGUAGE'},
 ua:{online:'Онла����н · локально',total:'Усього апгрейдів',topup:'Поповнити',likes:'Бонус спільноти',gifts:'Щоденний подарунок',likeText:'Дякуємо за підтримку UPGRADER. Ваш віртуальний бонус готовий.',claim:'ОТРИМАТИ 250 МОНЕТ',claimed:'ОТРИМАНО',giftText:'Відкрийте щоденну віртуальну нагороду.',open:'ВІДКРИТИ ПОДАРУНОК',skins:'МОЇ СКІНИ',market:'М��РКЕТ',shop:'МАГАЗИН',empty:'Ваш інвентар порожній',emptySub:'Купіть скін у Маркеті або виграйте апгрейд.',selectSource:'Оберіть скіни або баланс.',selectTarget:'Оберіть скін для апгрейду',upgrade:'Апгрейд',balance:'Сума балансу:',settings:'МОВА'}
} as const
function Header({ state, sound, mode, onMode, onSound, onTopup, onProfile, onLanguage, onRewards }:{ state:GameState; sound:boolean; mode:GameMode; onMode:(mode:GameMode)=>void; onSound:()=>void; onTopup:()=>void; onProfile:()=>void; onLanguage:(language:'en'|'ua')=>void; onRewards:()=>void }) {
  const [menuOpen,setMenuOpen]=useState(false); const wonChances=state.history.filter(item=>item.won).map(item=>item.chance); const best=wonChances.length?Math.min(...wonChances):0; const t=copy[state.language]
  return <header className="topbar">
    <div className="language-flags" aria-label={t.settings}><button className={state.language==='en'?'active':''} onClick={()=>onLanguage('en')} aria-label="English">EN</button><button className={state.language==='ua'?'active':''} onClick={()=>onLanguage('ua')} aria-label="Українська">UA</button></div>
    <div className="brand"><div className="mode-menu"><button className="mode-menu-trigger" aria-label="Open game modes" aria-expanded={menuOpen} onClick={()=>setMenuOpen(open=>!open)}><Menu aria-hidden="true"/></button>{menuOpen&&<div className="mode-menu-list" role="menu">{(['upgrader','crash','mines','cases','roulette','tower','plinko'] as GameMode[]).map((item,index)=><button key={item} className={mode===item?'active':''} role="menuitem" onClick={()=>{onMode(item);setMenuOpen(false)}}><span aria-hidden="true">{String(index+1).padStart(2,'0')}</span><b className="mode-menu-label">{item==='roulette'?'Roulette':item[0].toUpperCase()+item.slice(1)}</b></button>)}</div>}</div><img className="brand-logo" src="/upgrader-brand.svg" alt="" aria-hidden="true"/><b>{mode.toUpperCase()}</b><Headphones aria-hidden="true"/></div>
    <OnlineCounter/>
    <div className="player-stat"><strong>{state.nickname??'Player'}</strong><span>Best drop chance: {best.toFixed(2)}%</span></div>
    <div className="header-spacer"/>
    <LevelBadge casino={state.casino} onOpen={onRewards}/>
    <button className="circle-action" aria-label="Sound" onClick={onSound}>{sound?<Volume2/>:<VolumeX/>}</button>
    <button className="balance"><b>{money(state.balance)}</b><Mark small/></button>
    <button className="topup" onClick={onTopup}><Wallet/>{t.topup}</button>
    <button className="avatar" onClick={onProfile} aria-label="Open player profile"><CircleUserRound/></button>
  </header>
}

function LiveFeed({history,allSkins,nickname}:{history:History[];allSkins:Skin[];nickname:string}){
 const sevenDaysAgo=Date.now()-7*24*60*60*1000
 const recent=history.filter(item=>item.won&&(!item.createdAt||Date.parse(item.createdAt)>=sevenDaysAgo)).map(item=>({item,skin:allSkins.find(s=>`${s.weapon} ${s.name}`===item.target)})).filter(row=>row.skin)
 const topDrop=recent.reduce<(typeof recent)[number]|null>((best,row)=>!best||row.skin!.price>best.skin!.price?row:best,null)
 const wins=topDrop?[topDrop,...recent.filter(row=>row.item.id!==topDrop.item.id).sort((a,b)=>Date.parse(b.item.createdAt??'')-Date.parse(a.item.createdAt??''))]:[]
 return <aside className="feed" aria-label="Latest drops">
    <div className="feed-heading"><b>DROPS</b><span>{wins.length} won</span></div>
    {wins.length===0?<div className="feed-empty"><Mark/><strong>No drops yet</strong><p>Won skins will appear here.</p></div>:wins.map(({item,skin},i)=><article key={item.id} className={i===0?'feed-card jackpot':'feed-card'}>
      <div className="drop-info"><small className="drop-player">{item.player??nickname}</small><span className="chance-mini"><Mark small/><b>{item.chance.toFixed(2)} %</b></span><span className="drop-price"><b>{money(skin!.price)}</b></span><strong>{skin!.weapon}</strong><p>{skin!.name}</p>{i===0&&<em>★ BEST DROP (7d)</em>}</div>
      <SkinImage className="drop-skin-image" src={skin!.image} alt={`${skin!.weapon} ${skin!.name}`} priority={i<3}/>
    </article>)}
  </aside>
}

function SkinCard({ skin, selected, onClick }:{skin:Skin;selected:boolean;onClick:()=>void}){
  return <button className={`skin-card ${skin.rarity} ${selected?'selected':''}`} style={selected?undefined:{borderColor:rarityColor(skin)}} onClick={onClick}>
    <span className="skin-price">{money(skin.price)}<Mark small/></span>
    <SkinImage src={skin.image} alt={`${skin.weapon} ${skin.name}`}/>
    <span>{skin.weapon}</span><strong>{skin.name}</strong><b>{money(skin.price)} <Mark small/></b>
  </button>
}

function CatalogTools({from,to,onFrom,onTo,ascending,onSort,budgetShortcuts}:{from:string;to:string;onFrom:(value:string)=>void;onTo:(value:string)=>void;ascending:boolean;onSort:()=>void;budgetShortcuts?:{label:string;onClick:()=>void;disabled:boolean}[]}){
 return <div className="catalog-tools"><label><Mark small/><input inputMode="decimal" placeholder="from" value={from} onChange={event=>onFrom(event.target.value)}/></label><label><Mark small/><input inputMode="decimal" placeholder="to" value={to} onChange={event=>onTo(event.target.value)}/></label><button onClick={onSort} aria-label={ascending?'Sort expensive first':'Sort cheap first'} title={ascending?'Cheap → expensive':'Expensive → cheap'}><ArrowUpDown/><span>{ascending?'↑':'↓'}</span></button>{budgetShortcuts&&<div className="budget-shortcuts" aria-label="Affordable skin shortcuts">{budgetShortcuts.map(shortcut=><button key={shortcut.label} disabled={shortcut.disabled} onClick={shortcut.onClick}>{shortcut.label}</button>)}</div>}</div>
}

function MarketCard({skin,quantity,onChange}:{skin:Skin;quantity:number;onChange:(value:number)=>void}){
 const add=()=>onChange(quantity+1)
 return <article className={`skin-card market-card ${skin.rarity}`} style={{borderColor:rarityColor(skin)}} role="button" tabIndex={0} aria-label={`Add ${skin.weapon} ${skin.name} to cart`} onClick={add} onKeyDown={event=>{if((event.key==='Enter'||event.key===' ')&&!event.nativeEvent.isComposing&&event.keyCode!==229){event.preventDefault();add()}}}><span className="skin-price">{money(skin.price)}<Mark small/></span><SkinImage src={skin.image} alt={`${skin.weapon} ${skin.name}`}/><span>{skin.weapon}</span><strong>{skin.name}</strong><div className="quantity-control"><button onClick={event=>{event.stopPropagation();onChange(Math.max(0,quantity-1))}} aria-label="Remove one"><Minus/></button><b>{quantity}</b><button onClick={event=>{event.stopPropagation();add()}} aria-label="Add one"><Plus/></button></div></article>
}

function EmptySlot({title,sub}:{title:string;sub:string}){ return <section className="weapon-slot"><h3>{title}</h3><p>{sub}</p><div className="ghost-gun"><Mark/></div></section> }

function Modal({ children, title, onClose, wide=false }:{children:React.ReactNode;title:string;onClose:()=>void;wide?:boolean}){
  useEffect(()=>{const fn=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[onClose])
  return <div className="overlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`modal ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-label={title}><div className="modal-title"><h2>{title}</h2><button onClick={onClose} aria-label="Close"><X/></button></div>{children}</section></div>
}

function NicknameModal({onSave}:{onSave:(nickname:string)=>void}){
 const [nickname,setNickname]=useState('')
 const submit=(event:React.FormEvent)=>{event.preventDefault();const clean=nickname.trim().replace(/\s+/g,' ').slice(0,20);if(clean.length>=2)onSave(clean)}
 return <div className="overlay"><section className="modal nickname-modal" role="dialog" aria-modal="true" aria-labelledby="nickname-title"><div className="modal-title"><h2 id="nickname-title">CHOOSE YOUR NICKNAME</h2></div><form onSubmit={submit}><p>This nickname is permanent and will be shown above your drops.</p><input autoFocus minLength={2} maxLength={20} value={nickname} onChange={event=>setNickname(event.target.value)} placeholder="Your nickname"/><button className="yellow-button" disabled={nickname.trim().length<2}>CONTINUE</button></form></section></div>
}

function TopupModal({state,setState,operationLock,setOperationLock,onClose}:{state:GameState;setState:React.Dispatch<React.SetStateAction<GameState>>;operationLock:boolean;setOperationLock:React.Dispatch<React.SetStateAction<boolean>>;onClose:()=>void}){
 const [pop,setPop]=useState<{id:number;x:number;y:number;clicks:number}|null>(null)
 const [now,setNow]=useState(()=>Date.now())
 const pendingClicks=useRef(0); const clickFrame=useRef<number|null>(null); const latestPoint=useRef({x:0,y:0})
 const flushClicks=()=>{clickFrame.current=null;const clicks=pendingClicks.current;pendingClicks.current=0;if(!clicks)return;const valuePerClick=5*state.multiplier;setState(s=>({...s,balance:applyClickBurst(s.balance,clicks,valuePerClick,MAX_BALANCE)}));setPop({id:performance.now(),x:latestPoint.current.x,y:latestPoint.current.y,clicks})}
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),250);return()=>{window.clearInterval(timer);if(clickFrame.current)window.cancelAnimationFrame(clickFrame.current)}},[])
 useEffect(()=>{if(!pop)return;const timer=window.setTimeout(()=>setPop(null),350);return()=>window.clearTimeout(timer)},[pop])
 const click=(e:React.MouseEvent<HTMLButtonElement>)=>{pendingClicks.current+=1;latestPoint.current={x:e.nativeEvent.offsetX,y:e.nativeEvent.offsetY};if(clickFrame.current===null)clickFrame.current=window.requestAnimationFrame(flushClicks)}
 const [purchaseX3Lock,setPurchaseX3Lock]=useState(false)
 const buyX3=()=>{if(purchaseX3Lock||state.multiplier===3||state.credits<39)return;setPurchaseX3Lock(true);setState(s=>({...s,credits:s.credits-39,multiplier:3}));window.setTimeout(()=>setPurchaseX3Lock(false),500)}
 const status=getCoinFarmStatus(state.coinFarm,now)
 const claim=()=>{if(operationLock)return;const result=claimCoinSlot(state.coinFarm,now);if(!result.reward)return;setOperationLock(true);setState(s=>({...s,balance:Math.min(MAX_BALANCE,s.balance+result.reward),coinFarm:result.farm}));window.setTimeout(()=>setOperationLock(false),300)}
 const seconds=Math.ceil(status.remainingMs/1000)
 return <Modal title="COIN FARM AND MINI-GAME" onClose={onClose} wide><div className="shop-grid">
  <div className="clicker-pane"><div className="clicker-heading"><h3>Click and get coins!</h3><p>Press anywhere inside the field · +{5*state.multiplier} coins per click</p></div><button className="click-field" onClick={click} aria-label={`Click to earn ${5*state.multiplier} coins`}>{Array.from({length:130}).map((_,i)=><i key={i}/>)}{pop&&<b key={pop.id} style={{left:pop.x,top:pop.y}}>+{pop.clicks*5*state.multiplier}</b>}</button><div className="pass"><span>3X</span><div><b>Want to earn X3 profit?</b><p>Triple profit in the Clicker game</p></div><button className="yellow-button" disabled={purchaseX3Lock||state.multiplier===3||state.credits<39} onClick={buyX3}>{state.multiplier===3?'X3 ACTIVE':'BUY — 39 R$'}</button></div></div>
  <div className="coin-farm"><div className="farm-heading"><div><span>AUTOMATIC FARM</span><h3>Up to 15,000 coins</h3></div><Coins aria-hidden="true"/></div><p className="farm-copy">One 5,000 coin charge fills every minute. Up to three charges wait for you; claim one and the empty slot starts charging again from zero.</p><div className="farm-slots">{Array.from({length:MAX_COIN_SLOTS},(_,index)=>{const ready=index<status.readySlots;const active=index===status.activeSlot&&!status.isFull;const progress=ready?100:active?status.activeProgress*100:0;return <article key={index} className={`${ready?'ready ':''}${active?'active':''}`}><div className="slot-top"><span>CHARGE {index+1}</span><b>{ready?'READY':active?`${seconds}s`:'QUEUED'}</b></div><Coins aria-hidden="true"/><strong>{COIN_SLOT_VALUE.toLocaleString()} Coins</strong><div className="slot-progress" aria-hidden="true"><i style={{width:`${progress}%`}}/></div></article>})}</div><div className="farm-summary"><span>{status.readySlots} of {MAX_COIN_SLOTS} ready</span><strong>{(status.readySlots*COIN_SLOT_VALUE).toLocaleString()} Coins stored</strong></div><button className="yellow-button" disabled={!status.readySlots} onClick={claim}>{status.readySlots?`CLAIM 5,000 COINS`:'FARMING IN PROGRESS'}</button></div>
 </div></Modal>
}

function ProfileModal({state,setState,allSkins,onClose}:{state:GameState;setState:React.Dispatch<React.SetStateAction<GameState>>;allSkins:Skin[];onClose:()=>void}){
 const [selected,setSelected]=useState<string[]>([]); const [code,setCode]=useState(''); const [confirmReset,setConfirmReset]=useState(false); const inventory=state.inventory.map(instance=>({instance,skin:allSkins.find(s=>s.id===skinIdFromInstance(instance))!})).filter(row=>row.skin); const total=inventory.reduce((a,row)=>a+row.skin.price,0)
 const sell=(ids:string[])=>{const uniqueOwned=[...new Set(ids)].filter(id=>state.inventory.includes(id));if(!uniqueOwned.length)return;const sum=uniqueOwned.reduce((a,id)=>a+(allSkins.find(s=>s.id===skinIdFromInstance(id))?.price||0),0);setState(s=>({...s,balance:s.balance+sum,inventory:s.inventory.filter(id=>!uniqueOwned.includes(id))}));setSelected([])}
 const [promoLock,setPromoLock]=useState(false)
 const promo=()=>{if(promoLock)return;const c=code.trim().toUpperCase();if((c==='UPGRADE' || c==='WELCOME')&&!state.promo.includes(c)){setPromoLock(true);setState(s=>({...s,balance:Math.min(MAX_BALANCE,s.balance+500*ECONOMY_SCALE),promo:[...s.promo,c]}));setCode('');window.setTimeout(()=>setPromoLock(false),500)}}
 return <Modal title="PLAYER PROFILE" onClose={onClose}><div className="profile-head"><div className="profile-avatar"><CircleUserRound/></div><div><h3>{state.nickname}</h3><p>Total improvements: <b>{state.upgrades}</b></p></div><span>—</span><div className="promo"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="PROMOCODE..."/><button onClick={promo}>ENTER</button></div></div>
 <div className="profile-day-stats" aria-label="Player statistics"><div><span>WON TODAY</span><b className="positive">{money(state.casino.dayWon)}</b></div><div><span>BEST WIN TODAY</span><b>{money(state.casino.dayBestWin)}</b></div><div><span>ALL-TIME BEST WIN</span><b>{money(state.casino.biggestWin)}</b></div><div><span>BEST WIN STREAK</span><b>{state.casino.bestStreak}×</b></div></div>
 <div className="inventory-label"><div><b>MY INVENTORY FOR SALE</b><span>Inventory for: {money(total)} <Mark small/></span></div><strong>Selected for: {money(selected.reduce((a,id)=>a+(allSkins.find(s=>s.id===skinIdFromInstance(id))?.price||0),0))} <Mark small/></strong></div>
 <div className="profile-inventory">{inventory.length?inventory.map(({instance,skin})=><SkinCard key={instance} skin={skin} selected={selected.includes(instance)} onClick={()=>setSelected(x=>x.includes(instance)?x.filter(id=>id!==instance):[...x,instance])}/>):<p>Your inventory is empty.</p>}</div>
 <div className="profile-actions"><button disabled={!selected.length} onClick={()=>sell(selected)}>SELL THE SELECTED</button><button disabled={!inventory.length} onClick={()=>sell(state.inventory)}>SELL ALL</button></div>
 {state.history.length>0&&<div className="history"><b>RECENT UPGRADES</b>{state.history.slice(0,4).map(h=><span key={h.id} className={h.won?'won':'lost'}>{h.won?'SUCCESS':'FAILED'} · {h.target} · {h.chance.toFixed(2)}%</span>)}</div>}
 <details className="advanced-settings"><summary>ADVANCED SETTINGS</summary><div className="danger-zone"><div><b>RESET ALL PROGRESS</b><p>Deletes your balance, inventory, upgrades, X3, promo codes and history. Your balance returns to 5,000 coins.</p></div><button className="reset-button" onClick={()=>setConfirmReset(true)}>RESET GAME</button></div></details>
 {confirmReset&&<div className="reset-confirm" role="alertdialog" aria-modal="true" aria-labelledby="reset-title"><div><h3 id="reset-title">RESET EVERYTHING?</h3><p>This cannot be undone. All local progress will be deleted and your new balance will be 5,000 coins.</p><div><button onClick={()=>setConfirmReset(false)}>CANCEL</button><button className="reset-button" onClick={()=>{localStorage.removeItem('upgrader-game-v2');setState({...initial,coinFarm:{readySlots:0,cycleStartedAt:Date.now()}});setSelected([]);setConfirmReset(false);onClose()}}>YES, RESET ALL</button></div></div></div>}
 </Modal>
}

function CartModal({cart,skins,state,setState,operationLock,setOperationLock,onChange,onClose}:{cart:Record<string,number>;skins:Skin[];state:GameState;setState:React.Dispatch<React.SetStateAction<GameState>>;operationLock:boolean;setOperationLock:React.Dispatch<React.SetStateAction<boolean>>;onChange:(id:string,value:number)=>void;onClose:()=>void}){
 const rows=Object.entries(cart).filter(([,quantity])=>quantity>0).map(([id,quantity])=>({skin:skins.find(item=>item.id===id)!,quantity})).filter(row=>row.skin)
 const total=rows.reduce((sum,row)=>sum+row.skin.price*row.quantity,0)
 const buy=()=>{if(!rows.length||state.balance<total||operationLock)return;setOperationLock(true);setState(current=>({...current,balance:current.balance-total,inventory:[...current.inventory,...rows.flatMap(row=>Array.from({length:row.quantity},()=>instanceId(row.skin.id)))]}));rows.forEach(row=>onChange(row.skin.id,0));onClose();window.setTimeout(()=>setOperationLock(false),300)}
 return <Modal title="SHOPPING CART" onClose={onClose}><div className="cart-list">{rows.map(({skin,quantity})=><article key={skin.id}><SkinImage src={skin.image} alt={`${skin.weapon} ${skin.name}`} priority/><div><b>{skin.name}</b><span>{skin.weapon}</span></div><div className="cart-quantity"><button disabled={quantity<=1} onClick={()=>onChange(skin.id,Math.max(1,quantity-1))} aria-label={`Decrease ${skin.name} quantity`}><Minus/></button><b>{quantity}</b><button onClick={()=>onChange(skin.id,quantity+1)} aria-label={`Increase ${skin.name} quantity`}><Plus/></button></div><strong>{money(skin.price*quantity)} <Mark small/></strong><button className="cart-delete" onClick={()=>onChange(skin.id,0)}>DEL</button></article>)}{!rows.length&&<p>Your cart is empty.</p>}</div><div className="cart-total"><b>Result: {money(total)} <Mark small/></b><button className="cart-buy" disabled={!rows.length||state.balance<total} onClick={buy}>BUY ALL SKINS FROM THE CART</button></div></Modal>
}


export function UpgraderApp({initialCatalog}:{initialCatalog:Skin[]}){
 const [operationLock,setOperationLock]=useState(false)
 const [mode,setMode]=useState<GameMode>('upgrader')
 const [state,setState]=useState<GameState>(()=>({...initial,coinFarm:{readySlots:0,cycleStartedAt:Date.now()}})); const [ready,setReady]=useState(false); const [sound,setSound]=useState(true); const [modal,setModal]=useState<'topup'|'profile'|'cart'|'rewards'|null>(null); const [inventoryTab,setInventoryTab]=useState<'skins'|'market'>('skins'); const [page,setPage]=useState(0); const [catalogPage,setCatalogPage]=useState(0); const [source,setSource]=useState<string[]>([]); const [target,setTarget]=useState<Skin|null>(null); const [cash,setCash]=useState(0); const [query,setQuery]=useState(''); const [rolling,setRolling]=useState(false); const [result,setResult]=useState<'win'|'lose'|null>(null); const [wheelRotation,setWheelRotation]=useState(0); const [cart,setCart]=useState<Record<string,number>>({}); const [skinFilters,setSkinFilters]=useState<CatalogState>({ascending:true,from:'',to:''}); const [marketFilters,setMarketFilters]=useState<CatalogState>({ascending:true,from:'',to:''}); const [shopFilters,setShopFilters]=useState<CatalogState>({ascending:true,from:'',to:''}); const [errorMessage,setErrorMessage]=useState('')
 const allSkins=initialCatalog.length?initialCatalog:skins
 useEffect(()=>{try{const raw=localStorage.getItem('upgrader-game-v2');if(raw){const validIds=new Set(allSkins.map(s=>s.id));const saved=normalizeGameState(JSON.parse(raw),initial,validIds,Date.now()) as GameState;if(saved.balance===500||saved.balance===1000||saved.balance===2000||saved.balance===2000*ECONOMY_SCALE)saved.balance=5000;setState(saved)}}catch{localStorage.removeItem('upgrader-game-v2')}setReady(true)},[allSkins])
 useEffect(()=>{if(ready){try{localStorage.setItem('upgrader-game-v2',JSON.stringify(state))}catch{setErrorMessage('Progress could not be saved on this device.')}}},[state,ready])
 useEffect(()=>{if(rolling)return;setSource(current=>current.filter((id,index)=>state.inventory.includes(id)&&current.indexOf(id)===index));setCash(current=>Math.min(Math.max(0,current),state.balance))},[state.inventory,state.balance,rolling])
 const catalogStatus=initialCatalog.length?'ready':'fallback' as const
 const findSkin=(id:string)=>allSkins.find(s=>s.id===skinIdFromInstance(id))
 const applyFilters=(items:Skin[],filters:CatalogState)=>filterCatalog(items,'',filters.from,filters.to,filters.ascending)
 const ownedRows=state.inventory.map(instance=>({instance,skin:findSkin(instance)!})).filter(row=>row.skin); const owned=ownedRows.filter(row=>(!skinFilters.from||row.skin.price>=Number(skinFilters.from))&&(!skinFilters.to||row.skin.price<=Number(skinFilters.to))).sort((a,b)=>skinFilters.ascending?a.skin.price-b.skin.price:b.skin.price-a.skin.price); const marketSkins=applyFilters(allSkins,marketFilters); const stake=source.reduce((a,id)=>a+(findSkin(id)?.price||0),0)+cash; const chance=target?calculateChance(stake,target.price):0; const catalog=useMemo(()=>filterCatalog(allSkins.filter(s=>s.price>stake),query,shopFilters.from,shopFilters.to,shopFilters.ascending),[allSkins,stake,query,shopFilters]); const t=copy[state.language]
 const selectClosest=(desiredChance:number)=>{if(stake<=0)return;const desiredPrice=stake/(desiredChance/100);const candidates=allSkins.filter(item=>item.price>stake);const next=candidates.reduce<Skin|null>((best,item)=>!best||Math.abs(item.price-desiredPrice)<Math.abs(best.price-desiredPrice)?item:best,null);if(next){setTarget(next);const index=catalog.findIndex(item=>item.id===next.id);setCatalogPage(index<0?0:Math.floor(index/12))}}
 const setMarketBudget=(quantity:number)=>{const price=findAffordableCatalogPrice(allSkins,state.balance,quantity);if(price===null){showError(`No skin can be bought ${quantity}× with this balance.`);return}setMarketFilters(current=>({...current,from:String(price)}));setPage(0)}
 const showError=(message:string)=>{setErrorMessage(message);window.setTimeout(()=>setErrorMessage(''),3000)}
 const secureRandom=()=>{const value=new Uint32Array(1);crypto.getRandomValues(value);return value[0]/4294967296}
 const upgrade=()=>{
  if(!target||rolling||operationLock)return
  setOperationLock(true)
  const spinTarget=target; const spinSource=[...source]; const spinCash=cash
  if(!validateUpgradeStake(state.inventory,spinSource,spinCash,state.balance)){setSource(current=>current.filter(id=>state.inventory.includes(id)));setCash(Math.min(spinCash,state.balance));showError('Your stake changed. Select owned skins again.');setOperationLock(false);return}
  const spinStake=spinSource.reduce((sum,id)=>sum+(findSkin(id)?.price||0),0)+spinCash
  if(spinStake<=0||!Number.isFinite(spinTarget.price)||spinTarget.price<=spinStake){showError('Choose a target worth more than your stake.');setOperationLock(false);return}
  if(spinSource.some(instance=>skinIdFromInstance(instance)===spinTarget.id)){showError('You cannot upgrade a skin into the same skin.');setOperationLock(false);return}
  const spinChance=calculateChance(spinStake,spinTarget.price)
  if(spinChance<=0||spinChance>75){showError('Invalid upgrade chance.');setOperationLock(false);return}
  const won=isWinningRoll(secureRandom(),applyPity(spinChance,state.casino.lossStreak))
  const landing=upgradeLanding(won,spinChance,secureRandom)
  const extraTurns=4+Math.floor(secureRandom()*6)
  setState(current=>{const tracked=trackWager(current.casino,spinStake,secureRandom);return {...current,balance:Math.min(MAX_BALANCE,current.balance-spinCash+tracked.bonus),inventory:current.inventory.filter(id=>!spinSource.includes(id)),casino:tracked.casino}})
  setRolling(true);setResult(null);setModal(null)
  playUpgradeClick(sound)
  window.setTimeout(()=>startSpinSound(sound,2500),70)
  setWheelRotation(current=>current+extraTurns*360+((landing-(current%360)+360)%360))
  window.setTimeout(()=>{
   setState(current=>({...current,inventory:[...current.inventory,...(won?[instanceId(spinTarget.id)]:[])],upgrades:current.upgrades+1,casino:trackResult(current.casino,spinStake,won?spinTarget.price:0),history:[{id:crypto.randomUUID(),target:`${spinTarget.weapon} ${spinTarget.name}`,chance:spinChance,won,player:current.nickname??'Player',createdAt:new Date().toISOString()},...current.history].slice(0,50)}))
   setSource([]);setCash(0);setResult(won?'win':'lose');setRolling(false);setOperationLock(false);playUpgradeResult(sound,won)
  },2600)
 }
 return <main className="game-shell">
  <Header state={state} sound={sound} mode={mode} onMode={nextMode=>{if(!rolling&&!operationLock){setMode(nextMode);setResult(null)}}} onSound={()=>setSound(x=>{if(x)stopSpinSound();return !x})} onTopup={()=>{if(!rolling&&!operationLock)setModal('topup')}} onProfile={()=>{if(!rolling&&!operationLock)setModal('profile')}} onLanguage={language=>{if(!rolling&&!operationLock)setState(s=>({...s,language}))}} onRewards={()=>{if(!rolling)setModal('rewards')}}/><CasinoEventLayer sound={sound}/><LiveFeed history={state.history} allSkins={allSkins} nickname={state.nickname??'Player'}/>
  <div className="workspace">{mode==='plinko'?<PlinkoMode state={state} setState={setState} operationLock={operationLock} setOperationLock={setOperationLock} sound={sound}/>:mode==='cases'?<CasesMode state={state} setState={setState} allSkins={allSkins} operationLock={operationLock} setOperationLock={setOperationLock} sound={sound}/>:mode!=='upgrader'?<ArcadeMode mode={mode} state={state} setState={setState} operationLock={operationLock} setOperationLock={setOperationLock} sound={sound}/>:<><div className="wordmark"><Mark/><b>UPGRADER</b></div><button className="sound-toggle" onClick={()=>setSound(x=>{if(x)stopSpinSound();return !x})}>{sound?<Volume2/>:<VolumeX/>}</button>
   <div className="upgrade-stage"><div className="source-side">{source.length>0?<section className={`weapon-slot selected-source selected-count-${Math.min(source.length,4)}`}>{ownedRows.filter(row=>source.includes(row.instance)).map(({instance,skin})=><div key={instance} className="selected-skin-preview"><SkinImage src={skin.image} alt={`${skin.weapon} ${skin.name}`} priority/><strong>{skin.weapon} · {skin.name}</strong></div>)}</section>:<EmptySlot title={t.selectSource} sub={owned.length?'Choose a skin from MY SKINS below.':t.emptySub}/>}</div>
   <div className={`wheel-wrap ${result||''}`} style={{'--chance-start-soft':`${179.65 - chance * 1.8}deg`,'--chance-start':`${180 - chance * 1.8}deg`,'--chance-mid':`${180}deg`,'--chance-end':`${180 + chance * 1.8}deg`,'--chance-end-soft':`${180.35 + chance * 1.8}deg`} as React.CSSProperties}><div className="wheel-ticks"/><div className="chance-wheel"><div className="wheel-rotor"/><div className="wheel-center"><img src="/wheel-logo.svg" alt=""/><b>{chance.toFixed(2)} %</b>{result&&<span>{result==='win'?'SUCCESS':'FAILED'}</span>}</div><i className="wheel-pointer-orbit" style={{'--rotation':`${wheelRotation}deg`} as React.CSSProperties}><span/></i></div></div>
   <div className="target-side">{target?<section className="weapon-slot selected-target"><img src={target.image} alt={`${target.weapon} ${target.name}`}/><strong>{target.weapon} · {target.name}</strong></section>:<EmptySlot title="Select a skin for upgrade" sub="Choose an item from SHOP below."/>}</div></div>
   {errorMessage&&<div className="upgrade-error" role="alert">{errorMessage}</div>}<div className="controls">{source.length>0?<label>{t.balance} <b>{money(cash)} <Mark small/></b><input type="range" min="0" max={state.balance} step="1" value={cash} disabled={rolling} onChange={e=>setCash(+e.target.value)}/></label>:<div/>}<button className="upgrade-button" disabled={!target||!stake||rolling} onClick={upgrade}><img src="/upgrader-logo-v2.svg" alt="" aria-hidden="true"/>{rolling?'UPGRADING...':t.upgrade}</button><div className="quick">{[2,4,8].map(x=><button key={x} disabled={!stake||rolling} onClick={()=>selectClosest(100/x)}>x{x}</button>)}{[35,55,75].map(x=><button key={x} disabled={!stake||rolling} onClick={()=>selectClosest(x)}>{x}%</button>)}</div></div>
   <div className="inventory-grid"><section className="inventory-panel"><div className="inventory-tabs"><button className={inventoryTab==='skins'?'active':''} onClick={()=>setInventoryTab('skins')}><ShoppingBag aria-hidden="true"/> {t.skins}</button><button className={inventoryTab==='market'?'active':''} onClick={()=>setInventoryTab('market')}><Coins aria-hidden="true"/> {t.market}</button></div><CatalogTools from={inventoryTab==='skins'?skinFilters.from:marketFilters.from} to={inventoryTab==='skins'?skinFilters.to:marketFilters.to} onFrom={value=>{if(inventoryTab==='skins')setSkinFilters(s=>({...s,from:value}));else setMarketFilters(s=>({...s,from:value}));setPage(0)}} onTo={value=>{if(inventoryTab==='skins')setSkinFilters(s=>({...s,to:value}));else setMarketFilters(s=>({...s,to:value}));setPage(0)}} ascending={inventoryTab==='skins'?skinFilters.ascending:marketFilters.ascending} onSort={()=>{if(inventoryTab==='skins')setSkinFilters(s=>({...s,ascending:!s.ascending}));else setMarketFilters(s=>({...s,ascending:!s.ascending}));setPage(0)}} budgetShortcuts={inventoryTab==='market'?[{label:'Max',onClick:()=>setMarketBudget(1),disabled:state.balance<=0},{label:'1/2',onClick:()=>setMarketBudget(2),disabled:state.balance<=0},{label:'1/4',onClick:()=>setMarketBudget(4),disabled:state.balance<=0}]:undefined}/>{inventoryTab==='market'&&<div className="market-tools"><span>{Object.values(cart).reduce((sum,value)=>sum+value,0)} items selected</span><button onClick={()=>setModal('cart')} aria-label="Open shopping cart"><ShoppingCart/><b>{Object.values(cart).reduce((sum,value)=>sum+value,0)}</b></button></div>}<div className="skin-grid">{inventoryTab==='skins'?(owned.length===0?<div className="inventory-empty"><Mark/><b>{t.empty}</b><span>{t.emptySub}</span></div>:owned.map(({instance,skin})=><SkinCard key={instance} skin={skin} selected={source.includes(instance)} onClick={()=>{if(!rolling)setSource(x=>x.includes(instance)?x.filter(id=>id!==instance):[...x,instance])}}/>)):marketSkins.slice(page*12,page*12+12).map(s=><MarketCard key={`market-${s.id}`} skin={s} quantity={cart[s.id]??0} onChange={value=>setCart(current=>({...current,[s.id]:value}))}/>)}</div><div className="pager"><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))}><ChevronLeft/></button><span>{page+1} / {Math.max(1,Math.ceil(marketSkins.length/12))}</span><button disabled={(page+1)*12>=marketSkins.length} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button></div></section>
   <section className="catalog-panel"><div className="catalog-head"><h2 className="section-tab-title"><ShoppingBag aria-hidden="true"/> {t.shop}</h2><label><Search/><input placeholder="Search" value={query} onChange={e=>{setQuery(e.target.value);setCatalogPage(0)}}/></label><CatalogTools from={shopFilters.from} to={shopFilters.to} onFrom={value=>{setShopFilters(s=>({...s,from:value}));setCatalogPage(0)}} onTo={value=>{setShopFilters(s=>({...s,to:value}));setCatalogPage(0)}} ascending={shopFilters.ascending} onSort={()=>{setShopFilters(s=>({...s,ascending:!s.ascending}));setCatalogPage(0)}}/></div>{catalogStatus==='fallback'&&<div className="catalog-notice" role="status">Offline catalog active — core skins remain available.</div>}<div className="skin-grid">{catalog.slice(catalogPage*12,catalogPage*12+12).map(s=><SkinCard key={s.id} skin={s} selected={target?.id===s.id} onClick={()=>{if(!rolling)setTarget(s)}}/>)}</div><div className="pager"><button disabled={catalogPage===0} onClick={()=>setCatalogPage(p=>Math.max(0,p-1))}><ChevronLeft/></button><span>{catalogPage+1} / {Math.max(1,Math.ceil(catalog.length/12))}</span><button disabled={(catalogPage+1)*12>=catalog.length} onClick={()=>setCatalogPage(p=>p+1)}><ChevronRight/></button></div></section></div>
   </>}<footer><div><Mark/><b>SKINS UPGRADER</b></div><a className="telegram-contact" href="https://t.me/tbabirov" target="_blank" rel="noreferrer" aria-label="Open Telegram chat with tbabirov"><Send/><span>@tbabirov</span></a></footer>
  </div>
  {modal==='rewards'&&<RewardsModal state={state} setState={setState} onClose={()=>setModal(null)}/>} {modal==='topup'&&<TopupModal state={state} setState={setState} operationLock={operationLock} setOperationLock={setOperationLock} onClose={()=>setModal(null)}/>} {modal==='profile'&&<ProfileModal state={state} setState={setState} allSkins={allSkins} onClose={()=>setModal(null)}/>} {modal==='cart'&&<CartModal cart={cart} skins={allSkins} state={state} setState={setState} operationLock={operationLock} setOperationLock={setOperationLock} onChange={(id,value)=>setCart(current=>({...current,[id]:value}))} onClose={()=>setModal(null)}/>} {ready&&!state.nickname&&<NicknameModal onSave={nickname=>setState(s=>({...s,nickname}))}/>} 
 </main>
}
